// Code generated by "stringer -type=Suit"; DO NOT EDIT.

package card

import "strconv"

const _Suit_name = "SpadeClubDiamondHeart"

var _Suit_index = [...]uint8{0, 5, 9, 16, 21}

func (i Suit) String() string {
	if i < 0 || i >= Suit(len(_Suit_index)-1) {
		return "Suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Suit_name[_Suit_index[i]:_Suit_index[i+1]]
}
